### ISSUE TITLE
Implementing Level1 tasks. 

### ISSUE THREAD

**Issue by PaulisMatrix** [avinassh/go-caskdb#4]
1.  Support for deletion: Since its an append only log file, you don't actually go and update the value for the key but rather write a record with the same key but a sort of tombstone value. Once you load this in the KeyDir, the key will updated with the offset of the recent write(your tombstone value) and you can just check for this value. 
Related PR: https://github.com/avinassh/go-caskdb/pull/6/files

2.  CRC: Checksum is calculated based on the value that is being encoded and stored in the header. On requesting a kv record, we just check if the checksum matches i.e value is not corrupted. 

3.  Support for expiry: Have also added `SetX()` call which takes in an expiry time (time.Duration) after which the key will expire. We just note the expiry time in the header and check if they key has expired after X mins/secs. 

4.  Multi Data types for values: You can store different data types as values besides strings. This type information is stored in a separate header field called ValueType and check accordingly while decoding the value.
Note: Faced few issues while encoding a rune and int32 since both are of same type( rune is just an alias for int32) so have to define a custom type `UglyRune`. So if users want to store rune they need to use this custom type instead. 

At this point, our total headersize is 24bytes: `CRC(4B) + ExpiryTime(4B) + TimeStamp(4B) + KeySize(4B) + ValueSize(4B) + ValueType(4B)`

Refactored bits:
Separate Record struct for kv pair: https://github.com/avinassh/go-caskdb/pull/3/files#diff-4e36647f41c8fcc4fe2791fec1c379ac314053900486e3eb80e116b1c20ea731R101

Different Operations:
```
type Store interface {
	Get(key string) string
	Set(key string, value interface{}) error
	SetX(key string, value interface{}, expiry time.Duration) error
	Delete(key string) error
	ListKeys(string) <-chan Record
	Close() bool
} 
```
DiskStore{} implements this interface. 

Range scans is not implemented yet since it requires using a whole different ds(balanced trees like red black or avl trees) for storing the kv. Will do it later once I get a whole clarity on it.

**Comment by avinassh** [comment]
closed as same reasons mentioned in #3
